language: cpp
compiler: gcc
script: make && make test
#Can add notifications section as desired

before_install:
  - pip install --user cpp-coveralls
  
after_success:
  - coveralls --include "balanced.cpp" --gcov-options '\-lp'
